Team mTurk - Motivating Quality Work
================
Kevin Hanna, Kevin Stone, Changjing Zhao

  - [Motivating Quality Work](#motivating-quality-work)
      - [What motivates crowdsourced workers to do quality
        work?](#what-motivates-crowdsourced-workers-to-do-quality-work)
      - [Our Experiments](#our-experiments)
      - [Experiment 1, our first pilot](#experiment-1-our-first-pilot)
      - [Experiment 2, our second pilot](#experiment-2-our-second-pilot)
      - [Experiment 5, threats don’t
        work](#experiment-5-threats-dont-work)
      - [Experiment 6, threats still don’t
        work](#experiment-6-threats-still-dont-work)

## Motivating Quality Work

### What motivates crowdsourced workers to do quality work?

Our scoring metric measures the accuracy of the bounding box by
calculating the euclidean distance of the Turkers bounds to the correct
bounding. Therefor a **lower score is better**. When the treatment
should cause a negative reaction, the score should increase if our
hypothesis is correct.

### Our Experiments

1.  Pilot - Bound 20 images with negative treatment (Government
    Surveillance)
2.  Pilot - Bound a single image with negative treatment (Government
    Surveillance)
3.  Experiment - Bound a single image with positive treatment (Potential
    future work)
4.  Experiment - Increase subjects for experiment 3
5.  Experiment - Bound a single image with negative treatment, reward 2
    cents (Threat of not paying for poor performance)
6.  Experiment - Bound a single image with negative treatment, increased
    reward to 5 cents (Threat of not paying for poor performance)

| experiment\_no | is\_pilot | in\_treatment | count | mean\_score |  std\_dev |
| -------------: | --------: | ------------: | ----: | ----------: | --------: |
|              1 |         1 |             0 |   397 |   137.60402 | 295.29711 |
|              1 |         1 |             1 |   396 |   136.39470 | 296.29412 |
|              2 |         1 |             0 |   187 |    15.25847 |  36.79851 |
|              2 |         1 |             1 |   189 |    17.09362 |  42.27343 |
|              3 |         0 |             0 |    48 |    19.02776 |  23.08104 |
|              3 |         0 |             1 |    47 |    22.71446 |  36.73351 |
|              4 |         0 |             0 |    93 |    40.35981 | 139.47131 |
|              4 |         0 |             1 |    94 |    14.51884 |  25.36227 |
|              5 |         0 |             0 |    96 |    13.55187 |  23.01864 |
|              5 |         0 |             1 |    97 |    11.61424 |  11.00214 |
|              6 |         0 |             0 |    94 |    13.56319 |  20.70507 |
|              6 |         0 |             1 |    92 |    13.15357 |  17.04807 |

Experiment Data Summary

### Experiment 1, our first pilot

For our pilot, we gave the Turkers a negative treatment and asked that
they draw a single bounding box on each of 20 images. We first collected
some information about the subject through a survey and then randomly
assigned those subjects to treatment and control. Our primary goal was
to understand how our scoring scheme worked, gauge level of variance we
should expect in future experiments and test if our covariates collected
from our survey were helpful. We had high attrition and due to a
misunderstanding of the Mechanical Turk platform, our assignments to
treatment and control failed and we ended up with Turkers not in our
experiment in our results, and many ended up in both treatment and
control.

We were not able to trust any ATE, but we could at least see the
variance, which was exceptionally high.

![](team_mturk_experiments_files/figure-gfm/plot_experiment_1-1.png)<!-- -->![](team_mturk_experiments_files/figure-gfm/plot_experiment_1-2.png)<!-- -->

|  | mean\_worker\_score |
|  | :------------------ |
|  | Min. : 5.003        |
|  | 1st Qu.: 25.938     |
|  | Median :119.894     |
|  | Mean :135.288       |
|  | 3rd Qu.:178.160     |
|  | Max. :994.601       |
|  | NA’s :1             |

| in\_treatment | mean\_score | std\_dev |
| ------------: | ----------: | -------: |
|             0 |    146.7838 | 125.4300 |
|             1 |    118.8101 | 190.9985 |

``` r
#TODO Gauge if effort decreases with more HITTs
```

### Experiment 2, our second pilot

With the first pilot behind us, we decided we needed to focus on
increasing our statistical power and hypothesized that having more
subjects with fewer experiments would provide more statistical power.

![](team_mturk_experiments_files/figure-gfm/plot_experiment_2-1.png)<!-- -->![](team_mturk_experiments_files/figure-gfm/plot_experiment_2-2.png)<!-- -->

    ##  bounding_box_score
    ##  Min.   :  1.423   
    ##  1st Qu.:  5.054   
    ##  Median :  8.320   
    ##  Mean   : 16.178   
    ##  3rd Qu.: 13.498   
    ##  Max.   :489.540   
    ##  NA's   :3

| in\_treatment | mean\_score | std\_dev |
| ------------: | ----------: | -------: |
|             0 |    15.25847 | 36.79851 |
|             1 |    17.09362 | 42.27343 |

Even with a p-value of 0.655, this was progress. Our coefficient for in
treatment was still more likely due to random noise than not.

#### 2.1 Power Test

    ## 
    ##      Two-sample t test power calculation 
    ## 
    ##               n = 5756.986
    ##           delta = 1.835148
    ##              sd = 39.59534
    ##       sig.level = 0.05
    ##           power = 0.8
    ##     alternative = one.sided
    ## 
    ## NOTE: n is number in *each* group

To achieve the statistical power of 0.8 at the 0.05 confidence-level
with the variance we had in this experiement, we would require nearly
5,800 subjects in both control and treatment.

#### 2.2 Analysis

With this pilot, the only covariate we had was the amount of time each
Turker spent on the task. And working time acts as a control explaining
away some of the variance reducing the p-value for our target feature
from 0.45 to 0.39.

\=========================================================== Dependent
variable:  
————————————— bounding\_box\_score  
(1) (2)  
———————————————————– in\_treatment 1.835 1.903  
p = 0.656 p = 0.644

WorkTimeInSeconds 0.010  
p = 0.426

Constant 15.258\*\*\* 14.441\*\*\*  
p = 0.00000 p = 0.00001

|                                                                                                                                                                                                                                                                                                |
| :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Data Subset All All Observations 373 373 R2 0.001 0.002 Adjusted R2 -0.002 -0.003 Residual Std. Error 39.638 (df = 371) 39.657 (df = 370) F Statistic 0.200 (df = 1; 371) 0.418 (df = 2; 370) =========================================================== Note: *p\<0.1; **p\<0.05; ***p\<0.01 |
| \=============================================== Dependent variable: ————————— WorkTimeInSeconds                                                                                                                                                                                               |

in\_treatment -7.720  
p = 0.663

Constant 86.059\*\*\*  
p = 0.000

|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Data Subset All Observations 376 R2 0.001 Adjusted R2 -0.002 Residual Std. Error 171.347 (df = 374) F Statistic 0.191 (df = 1; 374) =============================================== Note: *p\<0.1; **p\<0.05; ***p\<0.01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| \#\#\#\# 2.3 Learnings from our second experiment.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| The estimated 11,600 subjects required to achieve the statistical power we needed was far too many, With a p-value of 0.389, even with the 11,600 subjects, we weren’t likely to find a statistically significant ATE. We need to change our experiment and collect more covariates.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| \#\#\# Experiment 3, incentive of future work.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| In both of our pilots, we used a treatment which we hypothesized would cause the Turkers in treatment to work less hard, and the ATE was positive, which in our scoring means the bounding was less accurate. We also wanted to test if a positive treatment would have a larger ATE, so the Turkers in treatment were told we were looking for Turkers to perform some future work with the hypothesis that if the Turkers though of the task as a test with the incentive of future work they would try harder. So we ran a small experiment to test this theory.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| \#\#\#\# 3.1 Simple regression analysis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| \`\`\`r e3\_mod\_1 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment)\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| stargazer(e3\_mod\_1, e2\_mod\_1, type = ‘text’, header = FALSE, table.placement = ‘h’, report=(’vc\*p’), add.lines = list(c(“Data Subset”, “All”, “All”, “\(x==1\)”))) \`\`\`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| `## ## ========================================================== ##                              Dependent variable: ##                     -------------------------------------- ##                               bounding_box_score ##                            (1)                 (2) ## ---------------------------------------------------------- ## in_treatment              3.687               1.835 ##                         p = 0.563           p = 0.656 ## ## Constant                19.028***           15.258*** ##                        p = 0.00004         p = 0.00000 ## ## ---------------------------------------------------------- ## Data Subset                All                 All ## Observations                92                 373 ## R2                        0.004               0.001 ## Adjusted R2               -0.007             -0.002 ## Residual Std. Error  30.379 (df = 90)   39.638 (df = 371) ## F Statistic         0.338 (df = 1; 90) 0.200 (df = 1; 371) ## ========================================================== ## Note:                          *p<0.1; **p<0.05; ***p<0.01`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| The first look was disappointing, the last p-value had gone up from 0.45 in the previous experiment to 0.463 in this, but we only used a quarter the number of subjects,and having that many fewer subjects could easily increase the probability that treatment and control look the same.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| \#\#\#\# 3.2 Analysis with covariates                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| In this experiment we asked the Turkers to answer some questions about the device they were using, their experience doing these types of tasks and some demographic info.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| \`\`\`r e3\_mod\_2 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+factor(monitor, exclude=NA))\] e3\_mod\_3 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+factor(didbf, exclude=NA))\] e3\_mod\_4 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+factor(age, exclude=NA))\] e3\_mod\_5 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+factor(edu, exclude=NA))\] e3\_mod\_6 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+factor(income, exclude=NA))\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| e3\_mod\_2 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+as.factor(monitor))\] e3\_mod\_3 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+as.factor(didbf))\] e3\_mod\_4 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+as.factor(age))\] e3\_mod\_5 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+as.factor(edu))\] e3\_mod\_6 \<- d\[experiment\_no==3, lm(bounding\_box\_score \~ in\_treatment+as.factor(income))\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| stargazer(e3\_mod\_1, e3\_mod\_2, e3\_mod\_3, e3\_mod\_4, e3\_mod\_5, e3\_mod\_6, type = ‘text’, header = FALSE, table.placement = ‘h’, report=(’vc\*p’), add.lines = list(c(“Data Subset”, “All”, “All”, “\(x==1\)”))) \`\`\`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| `## ## ===================================================================================================================================================== ##                                                                                 Dependent variable: ##                               ----------------------------------------------------------------------------------------------------------------------- ##                                                                                 bounding_box_score ##                                      (1)                  (2)                 (3)                  (4)                 (5)                (6) ## ----------------------------------------------------------------------------------------------------------------------------------------------------- ## in_treatment                        3.687                7.794               4.708                2.681               3.280              -0.015 ##                                   p = 0.563            p = 0.231           p = 0.470            p = 0.640           p = 0.613          p = 0.999 ## ## as.factor(monitor)largescreen                         -66.462*** ##                                                       p = 0.0004 ## ## as.factor(monitor)midsize                             -60.451*** ##                                                       p = 0.0005 ## ## as.factor(monitor)smalllaptop                         -57.383*** ##                                                        p = 0.002 ## ## as.factor(monitor)tablet                               -35.061* ##                                                        p = 0.064 ## ## as.factor(didbf)no                                                           7.732 ##                                                                            p = 0.612 ## ## as.factor(didbf)yes                                                          8.810 ##                                                                            p = 0.535 ## ## as.factor(age)31to40                                                                             -9.611 ##                                                                                                 p = 0.372 ## ## as.factor(age)41to50                                                                            97.704*** ##                                                                                                p = 0.00001 ## ## as.factor(age)lt21                                                                               -12.327 ##                                                                                                 p = 0.653 ## ## as.factor(edu)highschool                                                                                             -17.099 ##                                                                                                                     p = 0.438 ## ## as.factor(edu)masterorabove                                                                                          -14.161 ##                                                                                                                     p = 0.154 ## ## as.factor(edu)somecollege                                                                                            -15.051 ##                                                                                                                     p = 0.216 ## ## as.factor(income)gt30klt60k                                                                                                              7.338 ##                                                                                                                                        p = 0.371 ## ## as.factor(income)gt60klt90k                                                                                                              -3.268 ##                                                                                                                                        p = 0.762 ## ## as.factor(income)gt90k                                                                                                                   19.021 ##                                                                                                                                        p = 0.160 ## ## as.factor(income)lt10k                                                                                                                   -8.956 ##                                                                                                                                        p = 0.404 ## ## Constant                          19.028***            72.889***             9.539              18.250***           22.433***          18.375*** ##                                  p = 0.00004          p = 0.00004          p = 0.474           p = 0.00003         p = 0.00001         p = 0.002 ## ## ----------------------------------------------------------------------------------------------------------------------------------------------------- ## Data Subset                          All                  All                 x==1 ## Observations                          92                  92                   90                  92                   92                 92 ## R2                                  0.004                0.200               0.014                0.240               0.045              0.056 ## Adjusted R2                         -0.007               0.153               -0.021               0.205               0.001              0.001 ## Residual Std. Error            30.379 (df = 90)    27.850 (df = 86)     29.643 (df = 86)    26.982 (df = 87)     30.255 (df = 87)   30.251 (df = 86) ## F Statistic                   0.338 (df = 1; 90) 4.297*** (df = 5; 86) 0.393 (df = 3; 86) 6.879*** (df = 4; 87) 1.021 (df = 4; 87) 1.021 (df = 5; 86) ## ===================================================================================================================================================== ## Note:                                                                                                                     *p<0.1; **p<0.05; ***p<0.01` |
| The only covariate which seemed to act as any type of control was the education question, though it wasn’t very significant. However, all of the coeffecients for the screensize question were negative, and by a fairly significant ammount. The baseline value was cellphone, which can be significantly smaller than all the other types of screens. So we tested that on its own.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| \================================================== Dependent variable: ————————— bounding\_box\_score                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |

in\_treatment 2.239  
p = 0.710

monitor == “cellphone” 58.789\*\*\*  
p = 0.001

Constant 17.803\*\*\*  
p = 0.00005

|                                                                                                                                                                                                                              |
| :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Data Subset All Observations 92 R2 0.123 Adjusted R2 0.104 Residual Std. Error 28.655 (df = 89) F Statistic 6.268\*\*\* (df = 2; 89) ================================================== Note: *p\<0.1; **p\<0.05; ***p\<0.01 |
| \========================================================== Dependent variable: ————————————– WorkTimeInSeconds (1) (2)                                                                                                      |

in\_treatment 22.983 -7.720  
p = 0.766 p = 0.663

Constant 377.208\*\*\* 86.059\*\*\*  
p = 0.000 p = 0.000

|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Data Subset All All Observations 95 376 R2 0.001 0.001 Adjusted R2 -0.010 -0.002 Residual Std. Error 374.924 (df = 93) 171.347 (df = 374) F Statistic 0.089 (df = 1; 93) 0.191 (df = 1; 374) ========================================================== Note: *p\<0.1; **p\<0.05; ***p\<0.01                                                                                                                                                                                                                                                                                                                                                                              |
| \#\#\#\# 3.1 Power Test                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| \`\`\`r e3\_ate = d\[experiment\_no==3 & in\_treatment == 1, mean(bounding\_box\_score, na.rm=T)\] - d\[experiment\_no==3 & in\_treatment == 0, mean(bounding\_box\_score, na.rm=T)\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| e3\_sd = d\[experiment\_no==3, sd(bounding\_box\_score, na.rm=T)\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| power.t.test(delta=e3\_ate, sd=e3\_sd, sig.level = 0.05, power = 0.80, alternative = “one.sided”, n = NULL) \`\`\`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| `## ##      Two-sample t test power calculation ## ##               n = 834.1739 ##           delta = 3.686703 ##              sd = 30.26851 ##       sig.level = 0.05 ##           power = 0.8 ##     alternative = one.sided ## ## NOTE: n is number in *each* group`                                                                                                                                                                                                                                                                                                                                                                                                   |
| \#\#\# Experiment 4, More data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| \#TODO demographic info show how random it is.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r e4_mod_1 <- d[experiment_no %in% c(3,4), lm(bounding_box_score ~ in_treatment)] summary(e4_mod_1)`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| `## ## Call: ## lm(formula = bounding_box_score ~ in_treatment) ## ## Residuals: ##    Min     1Q Median     3Q    Max ## -30.80 -23.02 -12.37  -5.59 974.46 ## ## Coefficients: ##              Estimate Std. Error t value Pr(>\|t\|) ## (Intercept)    33.046      7.078   4.669 4.74e-06 *** ## in_treatment  -15.895     10.064  -1.579    0.115 ## --- ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 ## ## Residual standard error: 83.75 on 275 degrees of freedom ##   (5 observations deleted due to missingness) ## Multiple R-squared:  0.008989,   Adjusted R-squared:  0.005385 ## F-statistic: 2.494 on 1 and 275 DF,  p-value: 0.1154` |
| `r #d[experiment_no %in% c(1), .(sd(bounding_box_score)), keyby=WorkerId]`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| \================================================================================ Dependent variable: ———————————————————— WorkTimeInSeconds (1) (2) (3)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

in\_treatment -216.979\*\* 22.983 -7.720  
p = 0.016 p = 0.766 p = 0.663

Constant 596.369\*\*\* 377.208\*\*\* 86.059\*\*\*  
p = 0.000 p = 0.000 p = 0.000

|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Data Subset All All x==1 Observations 282 95 376 R2 0.021 0.001 0.001 Adjusted R2 0.017 -0.010 -0.002 Residual Std. Error 746.871 (df = 280) 374.924 (df = 93) 171.347 (df = 374) F Statistic 5.950\*\* (df = 1; 280) 0.089 (df = 1; 93) 0.191 (df = 1; 374) ================================================================================ Note: *p\<0.1; **p\<0.05; ***p\<0.01                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| \`\`\`r \#e4\_mod\_2 \<- d\[experiment\_no %in% c(3,4), lm(bounding\_box\_score \~ in\_treatment+is\_mobile+tried=(monitor=="" & mousetrackpad==""))\] \#summary(e4\_mod\_2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| e4\_mod\_2 \<- d\[experiment\_no %in% c(3,4), .(tried=as.numeric(monitor=="" & mousetrackpad==""), bounding\_box\_score, in\_treatment, is\_mobile, WorkTimeInSeconds)\] %\>% .\[, lm(bounding\_box\_score \~ in\_treatment+is\_mobile+tried)\] summary(e4\_mod\_2) \`\`\`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| `## ## Call: ## lm(formula = bounding_box_score ~ in_treatment + is_mobile + ##     tried) ## ## Residuals: ##    Min     1Q Median     3Q    Max ## -74.74 -17.37  -8.55  -2.25 930.51 ## ## Coefficients: (1 not defined because of singularities) ##              Estimate Std. Error t value Pr(>\|t\|) ## (Intercept)    25.475      7.167   3.554 0.000447 *** ## in_treatment  -12.460      9.825  -1.268 0.205791 ## is_mobile      51.518     16.535   3.116 0.002031 ** ## tried              NA         NA      NA       NA ## --- ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 ## ## Residual standard error: 81.47 on 273 degrees of freedom ##   (6 observations deleted due to missingness) ## Multiple R-squared:  0.0415, Adjusted R-squared:  0.03448 ## F-statistic:  5.91 on 2 and 273 DF,  p-value: 0.003072`      |
| `r e4_mod_2 <- d[experiment_no %in% c(3,4), .(tried=as.numeric(mousetrackpad==""), bounding_box_score, in_treatment, is_mobile, Reward)] %>% .[, lm(bounding_box_score ~ in_treatment+is_mobile+tried)] summary(e4_mod_2)`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| `## ## Call: ## lm(formula = bounding_box_score ~ in_treatment + is_mobile + ##     tried) ## ## Residuals: ##    Min     1Q Median     3Q    Max ## -79.68 -17.51  -8.75  -2.47 925.57 ## ## Coefficients: (1 not defined because of singularities) ##              Estimate Std. Error t value Pr(>\|t\|) ## (Intercept)    25.650      7.313   3.507 0.000531 *** ## in_treatment  -12.388     10.058  -1.232 0.219162 ## is_mobile      56.283     17.320   3.250 0.001304 ** ## tried              NA         NA      NA       NA ## --- ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 ## ## Residual standard error: 82.33 on 266 degrees of freedom ##   (13 observations deleted due to missingness) ## Multiple R-squared:  0.04525,    Adjusted R-squared:  0.03807 ## F-statistic: 6.303 on 2 and 266 DF,  p-value: 0.002115` |
| `r e4_mod_2 <- d[experiment_no %in% c(3,4), lm(bounding_box_score ~ in_treatment+is_mobile)] summary(e4_mod_2)`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `## ## Call: ## lm(formula = bounding_box_score ~ in_treatment + is_mobile) ## ## Residuals: ##    Min     1Q Median     3Q    Max ## -75.44 -18.89  -8.88  -2.36 929.81 ## ## Coefficients: ##              Estimate Std. Error t value Pr(>\|t\|) ## (Intercept)    27.285      7.234   3.772 0.000199 *** ## in_treatment  -14.181      9.936  -1.427 0.154659 ## is_mobile      50.409     16.750   3.010 0.002860 ** ## --- ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 ## ## Residual standard error: 82.55 on 274 degrees of freedom ##   (5 observations deleted due to missingness) ## Multiple R-squared:  0.0407, Adjusted R-squared:  0.0337 ## F-statistic: 5.812 on 2 and 274 DF,  p-value: 0.003371`                                                                                                                    |
| `r stargazer(e3_mod_1, e4_mod_1, type = 'text', header = FALSE, table.placement = 'h', add.lines = list(c("Data Subset", "All", "All", "$x==1$")))`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| \========================================================== Dependent variable: ————————————– bounding\_box\_score (1) (2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

in\_treatment 3.687 -15.895  
(6.340) (10.064)

Constant 19.028\*\*\* 33.046\*\*\*  
(4.385) (7.078)

|                                                                                                                                                                                                                                                                                           |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Data Subset All All Observations 92 277 R2 0.004 0.009 Adjusted R2 -0.007 0.005 Residual Std. Error 30.379 (df = 90) 83.748 (df = 275) F Statistic 0.338 (df = 1; 90) 2.494 (df = 1; 275) ========================================================== Note: *p\<0.1; **p\<0.05; ***p\<0.01 |
| `r stargazer(e4_mod_1, e4_mod_2, type = 'text', header = FALSE, table.placement = 'h', add.lines = list(c("Data Subset", "All", "All", "$x==1$")))`                                                                                                                                       |
| \============================================================== Dependent variable: —————————————— bounding\_box\_score (1) (2)                                                                                                                                                           |

in\_treatment -15.895 -14.181  
(10.064) (9.936)

is\_mobile 50.409\*\*\*  
(16.750)

Constant 33.046\*\*\* 27.285\*\*\*  
(7.078) (7.234)

|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Data Subset All All Observations 277 277 R2 0.009 0.041 Adjusted R2 0.005 0.034 Residual Std. Error 83.748 (df = 275) 82.547 (df = 274) F Statistic 2.494 (df = 1; 275) 5.812\*\*\* (df = 2; 274) ============================================================== Note: *p\<0.1; **p\<0.05; ***p\<0.01                                                                                                                                                                                                                                                                                                            |
| \`\`\`r e4\_mod\_3 \<- d\[experiment\_no %in% c(3,4), lm(bounding\_box\_score \~ in\_treatment+factor(monitor, exclude=c(NA)))\] e4\_mod\_4 \<- d\[experiment\_no %in% c(3,4), lm(bounding\_box\_score \~ in\_treatment+factor(didbf, exclude=c(NA)))\] e4\_mod\_5 \<- d\[experiment\_no %in% c(3,4), lm(bounding\_box\_score \~ in\_treatment+factor(age, exclude=NA))\] e4\_mod\_6 \<- d\[experiment\_no %in% c(3,4), lm(bounding\_box\_score \~ in\_treatment+factor(edu, exclude=NA))\] e4\_mod\_7 \<- d\[experiment\_no %in% c(3,4), lm(bounding\_box\_score \~ in\_treatment+factor(income, exclude=NA))\] |
| stargazer(e4\_mod\_3, e4\_mod\_4, e4\_mod\_5, e4\_mod\_6, e4\_mod\_7, type = ‘text’, header = FALSE, table.placement = ‘h’, add.lines = list(c(“Data Subset”, “All”, “All”, “\(x==1\)”))) \`\`\`                                                                                                                                                                                                                                                                                                                                                                                                                 |
| \================================================================================================================================================== Dependent variable: —————————————————————————————————— bounding\_box\_score (1) (2) (3) (4) (5)                                                                                                                                                                                                                                                                                                                                                              |

in\_treatment -11.593 -15.436 -15.364 -13.246 -15.622  
(9.947) (10.358) (10.083) (10.205) (9.981)

factor(monitor, exclude = c(NA))largescreen -36.873  
(32.733)

factor(monitor, exclude = c(NA))midsize -26.643  
(31.902)

factor(monitor, exclude = c(NA))notsure -39.773  
(51.355)

factor(monitor, exclude = c(NA))smalllaptop -28.512  
(32.632)

factor(monitor, exclude = c(NA))tablet 29.360  
(36.186)

factor(didbf, exclude = c(NA))no 10.107  
(23.372)

factor(didbf, exclude = c(NA))yes 20.584  
(21.478)

factor(age, exclude = NA)31to40 6.252  
(12.684)

factor(age, exclude = NA)41to50 1.080  
(20.540)

factor(age, exclude = NA)lt21 -18.433  
(30.134)

factor(age, exclude = NA)over50 -19.531  
(34.542)

factor(edu, exclude = NA)highschool -9.949  
(21.438)

factor(edu, exclude = NA)lthighschool -20.530  
(59.350)

factor(edu, exclude = NA)masterorabove 0.497  
(14.641)

factor(edu, exclude = NA)somecollege -9.642  
(12.514)

factor(income, exclude = NA)gt30klt60k 33.347\*\*\*  
(12.839)

factor(income, exclude = NA)gt60klt90k 1.730  
(15.998)

factor(income, exclude = NA)gt90k 14.138  
(20.109)

factor(income, exclude = NA)lt10k 3.463  
(14.509)

Constant 54.891\* 14.827 31.576\*\*\* 33.822\*\*\* 20.655\*\*  
(31.747) (20.399) (7.821) (8.470) (9.943)

-----

Data Subset All All x==1  
Observations 276 269 276 275 275  
R2 0.046 0.012 0.011 0.011 0.037  
Adjusted R2 0.025 0.001 -0.007 -0.008 0.019  
Residual Std. Error 81.864 (df = 269) 83.771 (df = 265) 83.205 (df =
270) 83.383 (df = 269) 82.269 (df = 269)  
F Statistic 2.179\*\* (df = 6; 269) 1.101 (df = 3; 265) 0.610 (df = 5;
270) 0.573 (df = 5; 269) 2.059\* (df = 5; 269)
==================================================================================================================================================
Note: *p\<0.1; **p\<0.05; ***p\<0.01

#### 4.1 Power Test

``` r
e4_ate = d[experiment_no %in% c(3, 4) & in_treatment == 1, mean(bounding_box_score, na.rm=T)] - d[experiment_no %in% c(3, 4) & in_treatment == 0, mean(bounding_box_score, na.rm=T)]

e4_sd = d[experiment_no %in% c(3, 4), sd(bounding_box_score, na.rm=T)]


power.t.test(delta=abs(e4_ate), 
             sd=e4_sd, 
             sig.level = 0.05,
             power = 0.80,
             alternative = "one.sided",
             n = NULL)
```

    ## 
    ##      Two-sample t test power calculation 
    ## 
    ##               n = 345.7973
    ##           delta = 15.89495
    ##              sd = 83.97393
    ##       sig.level = 0.05
    ##           power = 0.8
    ##     alternative = one.sided
    ## 
    ## NOTE: n is number in *each* group

``` r
power_curve <- function(x) {
  result = c()

  for (i in 1:length(x)) {
    new_n <- power.t.test(delta=abs(e4_ate), 
             sd=e4_sd, 
             sig.level = 0.05,
             power = NULL,
             alternative = "one.sided",
             n = x[i])["power"]
    
    result <- c(result, new_n)
  }
  
  return(result)
}

sig_curve <- function(x) {
  result = c()

  for (i in 1:length(x)) {
    new_n <- power.t.test(delta=abs(e4_ate), 
             sd=e4_sd, 
             sig.level = NULL,
             power = 0.8,
             alternative = "one.sided",
             n = x[i])["sig.level"]
    
    result <- c(result, new_n)
  }
  
  return(result)
}

delta_curve <- function(x) {
  result = c()

  for (i in 1:length(x)) {
    new_n <- power.t.test(delta=x[i], 
             sd=e4_sd, 
             sig.level = 0.05,
             power = 0.8,
             alternative = "one.sided",
             n = NULL)["n"]
    
    result <- c(result, new_n)
  }
  
  return(result)
}
curve(power_curve(x), 10, 1000)
```

![](team_mturk_experiments_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

``` r
#curve(sig_curve(x), 10, 1000)
#curve(delta_curve(x), 5, 20)
```

### Experiment 5, threats don’t work

``` r
e5_mod_1 <- d[experiment_no == 5, lm(bounding_box_score ~ in_treatment)]
summary(e5_mod_1)
```

    ## 
    ## Call:
    ## lm(formula = bounding_box_score ~ in_treatment)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -12.005  -7.388  -4.123   0.854 193.311 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    13.552      1.848   7.334 6.38e-12 ***
    ## in_treatment   -1.938      2.606  -0.743    0.458    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 18.01 on 189 degrees of freedom
    ##   (2 observations deleted due to missingness)
    ## Multiple R-squared:  0.002916,   Adjusted R-squared:  -0.00236 
    ## F-statistic: 0.5527 on 1 and 189 DF,  p-value: 0.4582

### Experiment 6, threats still don’t work

``` r
e6_mod_1 <- d[experiment_no == 6, lm(bounding_box_score ~ in_treatment)]
summary(e6_mod_1)
```

    ## 
    ## Call:
    ## lm(formula = bounding_box_score ~ in_treatment)
    ## 
    ## Residuals:
    ##    Min     1Q Median     3Q    Max 
    ## -12.02  -8.64  -6.39  -1.38 107.83 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   13.5632     1.9581   6.927 6.99e-11 ***
    ## in_treatment  -0.4096     2.7842  -0.147    0.883    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 18.98 on 184 degrees of freedom
    ## Multiple R-squared:  0.0001176,  Adjusted R-squared:  -0.005317 
    ## F-statistic: 0.02164 on 1 and 184 DF,  p-value: 0.8832

``` r
e6_mod_2 <- d[experiment_no %in% c(5,6), lm(bounding_box_score ~ in_treatment+(Reward == "$0.05"))]
summary(e6_mod_2)
```

    ## 
    ## Call:
    ## lm(formula = bounding_box_score ~ in_treatment + (Reward == "$0.05"))
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -12.399  -8.042  -5.148  -0.011 193.690 
    ## 
    ## Coefficients:
    ##                       Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)            13.1730     1.6439   8.013 1.44e-14 ***
    ## in_treatment           -1.1838     1.9033  -0.622    0.534    
    ## Reward == "$0.05"TRUE   0.7731     1.9034   0.406    0.685    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 18.48 on 374 degrees of freedom
    ##   (2 observations deleted due to missingness)
    ## Multiple R-squared:  0.001484,   Adjusted R-squared:  -0.003855 
    ## F-statistic: 0.278 on 2 and 374 DF,  p-value: 0.7575
