---
title: "Team mTurk - Image Bounding Scoring"
output: 
    github_document: default
    pdf_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(
    inputFile, encoding = encoding,
    output_format ='github_document')
    })
  
---

```{r setup, include=FALSE}
library(data.table)
library(dplyr)
library(rjson)
#library(knitr)
```

```{r}
# Read in the correct bounding cooridinates
pilot_d <- fread("../data/experiment_2/experiment_2_results.csv")
pilot_d[, log_bounding_box_score := log(bounding_box_score)]


head(pilot_d)
```

```{r}
worker_mean_score <- pilot_d[, .(score = mean(bounding_box_score), log_score = mean(log_bounding_box_score), in_treatment = as.integer(median(in_treatment))), keyby=WorkerId]

worker_mean_score[, plot(score, col=(in_treatment+1))]
worker_mean_score[, plot(log_score, col=c("black", "red")[in_treatment+1])]

worker_mean_score[in_treatment==0, hist(score, breaks=30)]
worker_mean_score[in_treatment==1, hist(score, breaks=30)]

summary(pilot_d[, .(bounding_box_score)])

```

```{r}
pilot_d[, mean(bounding_box_score, na.rm=T), keyby=in_treatment]

#mod <- pilot_d[bounding_box_score < 50, lm(bounding_box_score ~ in_treatment+bound_size)]
mod <- pilot_d[, lm(bounding_box_score ~ in_treatment)]
summary(mod)

#t.test(pilot_d[in_treatment == 1, bounding_box_score], pilot_d[in_treatment == 0, bounding_box_score])

```

```{r}
mod <- pilot_d[, lm(bounding_box_score ~ in_treatment+as.factor(q02.monitor))]
summary(mod)
```

```{r}
mod <- pilot_d[, lm(bounding_box_score ~ in_treatment+as.factor(q03.mousetrackpad))]
summary(mod)
```

```{r}
mod <- pilot_d[, lm(bounding_box_score ~ WorkTimeInSeconds)]
summary(mod)
```

```{r}
pilot_d[, mean(WorkTimeInSeconds, na.rm=T), keyby=in_treatment]

mod <- pilot_d[, lm(WorkTimeInSeconds ~ in_treatment)]
summary(mod)

```


```{r}
mod <- worker_mean_score[, lm(score ~ in_treatment)]
summary(mod)
```

```{r}
mod <- worker_mean_score[, lm(score ~ in_treatment)]
summary(mod)
```


```{r}
pilot_d[, mean(WorkTimeInSeconds)]
```



```{r}
pilot_d[, .N, keyby=WorkerId]
```

```{r}

pilot_d[, sum(in_treatment)]
```

```{r}

pilot_d[, mean(bounding_box_score), keyby=ImageId]
```


```{r}
pilot_d[, .N, keyby=WorkerId]

```

```{r}
mod <- pilot_d[(in_treatment==0 & bounding_box_score < 600) | in_treatment==1, lm(bounding_box_score ~ in_treatment+bound_size)]
summary(mod)
```

