---
title: "Team mTurk - Image Bounding Scoring"
output: 
    github_document: default
    pdf_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(
    inputFile, encoding = encoding,
    output_format ='github_document')
    })
  
---

```{r setup, include=FALSE}
library(data.table)
library(dplyr)
library(rjson)
```

```{r}
# Read the results from Mechanical Turk

get_result_data_pilot_1 <- function() {
  control <- fread("../data/pilot_1/Batch_3846852_batch_results_reg.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/pilot_1/Batch_3846847_batch_results_gov.csv")
  treatment[, in_treatment := 1]

  results <- rbind(control, treatment)
  results[, experiment_no := 1]
  results[, is_pilot := 1]

  return(results)
}


get_result_data_pilot_2 <- function() {
  control <- fread("../data/pilot_2/Batch_3847172_batch_results_reg.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/pilot_2/Batch_3847422_batch_results_gov.csv")
  treatment[, in_treatment := 1]
  
  results <- rbind(control, treatment)
  results[, experiment_no := 2]
  results[, is_pilot := 1]
  
  return(results)}

get_result_data_experiment_1 <- function() {
  control <- fread("../data/experiment_1/Batch_3849139_batch_results_norelationship.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/experiment_1/Batch_3849192_batch_results_relationship.csv")
  treatment[, in_treatment := 1]
  
  results <- rbind(control, treatment)

  results[, experiment_no := 3]
  results[, is_pilot := 0]
    
  results[, Input.image_url := "https://kstonedev.s3-us-west-2.amazonaws.com/W241/openimages/116257e7260fdb51.jpg"]
  return(results)
  
  
}


get_result_data_experiment_2 <- function() {
  control <- fread("../data/experiment_2/Batch_3851700_batch_results_norelationship.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/experiment_2/Batch_3851648_batch_results_relationship.csv")
  treatment[, in_treatment := 1]
  
  results <- rbind(control, treatment)

  results[, experiment_no := 4]
  results[, is_pilot := 0]
  
  results[, Input.image_url := "https://kstonedev.s3-us-west-2.amazonaws.com/W241/openimages/116257e7260fdb51.jpg"]
  return(results)

}

get_result_data_experiment_3 <- function() {
  control <- fread("../data/experiment_3/Batch_3852927_batch_results_2centscontrol.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/experiment_3/Batch_3853201_batch_results_2centscompperf.csv")
  treatment[, in_treatment := 1]
  
  results <- rbind(control, treatment)

  results[, experiment_no := 5]
  results[, is_pilot := 0]
  
  results[, Input.image_url := "https://kstonedev.s3-us-west-2.amazonaws.com/W241/openimages/116257e7260fdb51.jpg"]
  return(results)

}


get_result_data_experiment_4 <- function() {
  control <- fread("../data/experiment_4/Batch_3853433_batch_results_5cents.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/experiment_4/Batch_3853564_batch_results_5centscompperf.csv")
  treatment[, in_treatment := 1]
  
  results <- rbind(control, treatment)

  results[, experiment_no := 6]
  results[, is_pilot := 0]
  
  results[, Input.image_url := "https://kstonedev.s3-us-west-2.amazonaws.com/W241/openimages/116257e7260fdb51.jpg"]
  return(results)

}

get_result_data_experiment_5 <- function() {
  control <- fread("../data/experiment_5/Batch_3853897_batch_results_oneqn_relationship.csv")
  control[, in_treatment := 0]
  
  treatment <- fread("../data/experiment_5/Batch_3854419_batch_results_norelation_1qn.csv")
  treatment[, in_treatment := 1]
  
  results <- rbind(control, treatment)

  results[, experiment_no := 7]
  results[, is_pilot := 0]
  
  results[, Input.image_url := "https://kstonedev.s3-us-west-2.amazonaws.com/W241/openimages/116257e7260fdb51.jpg"]
  return(results)

}

get_result_data_all_experiments <- function() {
  mturk_results_pilot_1 <- get_result_data_pilot_1()
  mturk_results_pilot_2 <- get_result_data_pilot_2()
  mturk_results_dt_1 <- get_result_data_experiment_1()
  mturk_results_dt_2 <- get_result_data_experiment_2()
  mturk_results_dt_3 <- get_result_data_experiment_3()
  mturk_results_dt_4 <- get_result_data_experiment_4()
  mturk_results_dt_5 <- get_result_data_experiment_5()
  
  rbind(mturk_results_pilot_1, mturk_results_pilot_2, mturk_results_dt_1, mturk_results_dt_2, mturk_results_dt_3, mturk_results_dt_4, mturk_results_dt_5, fill=TRUE)
}



```




```{r}
# Read in the correct bounding cooridinates
image_coords_dt <- fread("../data/image_coords.csv")
image_coords_dt[, bound_size := (bottom-top)*(right-left)]
```

```{r}
convert_mturk_bounding <- function(mturk_bounding_boxes) {
  # Mechanical Turk provides results with double-quoted JSON consisting of:
  #   height
  #   width
  #   top
  #   left
  #   label

  # Converts to top-left and bottom-right coords
  
  # Replace double-quotes (assumes there are no empty values)
  mturk_bounding_boxes <- gsub("\"\"", "\"", mturk_bounding_boxes)
  bounding_boxes_list <- fromJSON(mturk_bounding_boxes)
  
  # If there is no bounding boxes for this HIT, return NULL
  if (length(bounding_boxes_list) < 1) {
    print("No rows")
    return(NULL)
  }
    
  top_results_list <- c()
  bottom_results_list <- c()
  right_results_list <- c()
  left_results_list <- c()
  
  for (bounding_box in bounding_boxes_list) {
    top = as.integer(bounding_box$top)
    left = as.integer(bounding_box$left)
    bottom = as.integer(top + bounding_box$height)
    right = as.integer(left + bounding_box$width)

    top_results_list <- c(top_results_list, top)
    bottom_results_list <- c(bottom_results_list, bottom)
    right_results_list <- c(right_results_list, right)
    left_results_list <- c(left_results_list, left)
  }


  ret_dt <- data.table(
    top = top_results_list,
    bottom = bottom_results_list,
    right = right_results_list,
    left = left_results_list
  )
    
  return(ret_dt)
}

extract_image_bounding_data <- function(dt) {
  # Iterate through data.table, separate bounding boxes in to new rows in case there are multiple bounding boxes in any images. 
  
  results_dt <- data.table()
  
  for (i in 1:nrow(dt)) {
    row <- dt[i, ]

    bounding_boxes_dt <- convert_mturk_bounding(row[, Answer.annotatedResult.boundingBoxes])
    
    if (is.null(bounding_boxes_dt)) {
      bounding_boxes_dt <- data.table(
        top = NA,
        bottom = NA,
        left = NA,
        right = NA
      )
    }
    
    # Add attributes for the HIT to bounding boxes
    bounding_boxes_dt[, HITId := row[, HITId]]
    bounding_boxes_dt[, HITTypeId := row[, HITTypeId]]
    bounding_boxes_dt[, Reward := row[, Reward]]
    bounding_boxes_dt[, AssignmentDurationInSeconds := row[, AssignmentDurationInSeconds]]
    bounding_boxes_dt[, WorkerId := row[, WorkerId]]
    bounding_boxes_dt[, AssignmentStatus := row[, AssignmentStatus]]
    bounding_boxes_dt[, LifetimeApprovalRate := row[, LifetimeApprovalRate]]
    bounding_boxes_dt[, Last30DaysApprovalRate := row[, Last30DaysApprovalRate]]
    bounding_boxes_dt[, Last7DaysApprovalRate := row[, Last7DaysApprovalRate]]
    bounding_boxes_dt[, WorkTimeInSeconds := row[, WorkTimeInSeconds]]
    
    bounding_boxes_dt[, experiment_no := row[, experiment_no]]
    bounding_boxes_dt[, is_pilot := row[, is_pilot]]
    

    # Compile responses in to columns
    bounding_boxes_dt$didbf <- ifelse(row$Answer._1donebf1.yes ==TRUE, "yes", 
                      ifelse(row$Answer._1donebf2.no == TRUE, "no", 
                      ifelse(row$Answer._1donebf3.dontknow == TRUE, "dontknow","NA")))
    
    bounding_boxes_dt$monitor <- ifelse(row$Answer._2monitor1.cellphone   ==TRUE, "cellphone", 
                      ifelse(row$Answer._2monitor2.tablet   == TRUE, "tablet",
                      ifelse(row$Answer._2monitor3.smalllaptop == TRUE, "smalllaptop",
                      ifelse(row$Answer._2monitor4.midsize == TRUE, "midsize",
                      ifelse(row$Answer._2monitor5.largescreen == TRUE, "largescreen",
                      ifelse(row$Answer._2monitor6.notsure == TRUE, "notsure","NA"))))))
    
    bounding_boxes_dt$mousetrackpad<-ifelse(row$Answer._3cursor1.mouse == TRUE, "mouse", 
                      ifelse(row$Answer._3cursor2.trackpad == TRUE, "trackpad",
                      ifelse(row$Answer._3cursor3.touchscreen == TRUE, "touchscreen",
                      ifelse(row$Answer._3cursor3.other == TRUE, "other","NA"))))
    
    bounding_boxes_dt$age<-ifelse(row$Answer._4age1.lt21 ==TRUE, "lto21", 
                      ifelse(row$Answer._4age2.21to30 == TRUE, "21to30",
                      ifelse(row$Answer._4age3.31to30 == TRUE, "31to40", 
                      #31to30 variable poorly named, but no impact, UI was correct. 
                      ifelse(row$Answer._4age4.41to50 == TRUE, "41to50",
                      ifelse(row$Answer._4age5.over50r == TRUE, "over50","NA")))))
    
    bounding_boxes_dt$income<-ifelse(row$Answer._5income1.lt10k ==TRUE, "lt10k", 
                      ifelse(row$Answer._5income2.gt10klt30k == TRUE, "10ktolt30k",
                      ifelse(row$Answer._5income3.gt30klt60k == TRUE, "gt30klt60k", 
                      ifelse(row$Answer._5income4.gt60klt90k == TRUE, "gt60klt90k",
                      ifelse(row$Answer._5income5.gt90k == TRUE, "gt90k","NA")))))
    
    bounding_boxes_dt$edu<-ifelse(row$Answer._6edu1.lthighschool ==TRUE, "lthighschool", 
                      ifelse(row$Answer._6edu2.highschool == TRUE, "highschool",
                      ifelse(row$Answer._6edu3.somecollege == TRUE, "somecollege", 
                      ifelse(row$Answer._6edu4.fouryearcollege == TRUE, "fouryearcollege",
                      ifelse(row$Answer._6edu5.masterorabove == TRUE, "masterorabove","NA")))))
    
    
    
    # is_mobile implies the use of cellphone or tablet
    #bounding_boxes_dt$is_mobile <- as.numeric((row$Answer._2monitor1.cellphone | 
    #                                             row$Answer._2monitor2.tablet | 
    #                                             row$Answer._3cursor3.touchscreen))
    bounding_boxes_dt$is_mobile <- bounding_boxes_dt$mousetrackpad == "touchscreen" | 
      bounding_boxes_dt$monitor %in% c("cellphone", "tablet")
    bounding_boxes_dt$is_cellphone <- bounding_boxes_dt$is_mobile
    
    # is_cellphone implies the use of cellphone only
    #bounding_boxes_dt$is_cellphone <- as.numeric(row$Answer._2monitor1.cellphone | row$Answer._3cursor3.touchscreen)
    
    
    
#    bounding_boxes_dt$mousetrackpad2<-ifelse(row$Answer._3cursor1.mouse == TRUE, "mouse", 
#                      ifelse(row$Answer._3cursor2.trackpad == TRUE, "trackpad",
#                      ifelse((row$Answer._2monitor1.cellphone | row$Answer._2monitor2.tablet), "touchscreen",
#                      ifelse(row$Answer._3cursor3.other == TRUE, "other","NA"))))

    
    bounding_boxes_dt[, ImageId := row[, Input.image_url]] # Column renamed
    bounding_boxes_dt[, in_treatment := row[, in_treatment]]
    
    # Concatinate to results
    results_dt <- rbind(results_dt, bounding_boxes_dt)
  }
  
  return(results_dt)
}

score_bounding_box <- function(true_coords, turker_coords) {
  # Calculate the difference in the top-right and bottom-left points
  
  top = as.integer(true_coords[, top]) - turker_coords[, top]
  right = true_coords[, right] - turker_coords[, right]
  first_distance <- sqrt(top^2 + right^2)

  bottom = as.integer(true_coords[, bottom]) - turker_coords[, bottom]
  left = true_coords[, left] - turker_coords[, left]
  second_distance <- sqrt(bottom^2 + left^2)
  
  return(first_distance + second_distance)
  
}

get_bounding_size <- function(ImageIds) {
  
  results <- c()
  for (iid in ImageIds) {
    results <- c(results, image_coords_dt[ImageId == iid, bound_size])
  }
  
  return(results)
}

score_mturk_results <- function(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row) {
  
  score_results = c()

  # Iterate through the turker results
  for (i in 1:nrow(formatted_mturk_image_boundings_dt)) {
    
    formatted_mturk_image_boundings_row <- formatted_mturk_image_boundings_dt[i, ]
    tmp_scoring_results = c()
    
    # Find the correct bounding
    matched_images_dt <- image_coords_dt[ImageId == formatted_mturk_image_boundings_row[, ImageId], ]

    bounding_box_score <- score_bounding_box(matched_images_dt[, ], formatted_mturk_image_boundings_row[, ])
    score_results <- c(score_results, bounding_box_score)
    
  }
  score_results
}

```

```{r}
# Prepare the mturk results

prep_pilot_1_data <- function() {

  mturk_results_dt <- get_result_data_pilot_1()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/pilot_1/pilot1_results.csv")
}

prep_pilot_2_data <- function() {

  mturk_results_dt <- get_result_data_pilot_2()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/pilot_2/pilot2_results.csv")
}

prep_experiment_1_data <- function() {

  mturk_results_dt <- get_result_data_experiment_1()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/experiment_1/experiment_1_results.csv")
}

prep_experiment_2_data <- function() {

  mturk_results_dt <- get_result_data_experiment_2()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/experiment_2/experiment_2_results.csv")
}

prep_experiment_3_data <- function() {

  mturk_results_dt <- get_result_data_experiment_3()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/experiment_3/experiment_3_results.csv")
}

prep_experiment_4_data <- function() {

  mturk_results_dt <- get_result_data_experiment_4()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/experiment_4/experiment_4_results.csv")
}


prep_experiment_5_data <- function() {

  mturk_results_dt <-get_result_data_experiment_5()
  
  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/experiment_5/experiment_5_results.csv")
}

prep__all_experiment_data <- function() {

  mturk_results_dt <- get_result_data_all_experiments()

  formatted_mturk_image_boundings_dt <- extract_image_bounding_data(mturk_results_dt)
  formatted_mturk_image_boundings_dt[, bound_size := get_bounding_size(ImageId)]
  formatted_mturk_image_boundings_dt[, bounding_box_score := 
                                       score_mturk_results(formatted_mturk_image_boundings_dt, formatted_mturk_image_boundings_row)]
  
  fwrite(formatted_mturk_image_boundings_dt, "../data/experiment_all/experiment_results.csv")
}

#prep_experiment_5_data()
prep__all_experiment_data()


```



